### PR TITLE
Added switch for auto-refresh

### PR DESCRIPTION
**Pull request by CITIZENDOT**
Users can opt-out from auto-refreshing by toggling this switch. 
However, by default, this will be turned on.

Preview:
---

Screenshot at 2021-05-09 16-46-44

### CODE REVIEW

**Comment by subodhk01** [comment]
@CITIZENDOT any particular reason to close the PR?

**Comment by CITIZENDOT** [comment]
Oh, I thought this project is inactive.

**Comment by subodhk01** [comment]
Actually, I didn't knew about the PR, got a notification when it got closed.
I'll review it!

**Comment by CITIZENDOT** [comment]
Sure. I'll create another PR as I deleted the fork of this.

**Pull request closed without merging**
