### PR TITLE
Added ladder by rating

### PR DESCRIPTION
**Pull request by abdulrcs**
Hey, I've had some extra time today and implemented the ladder by rating based on my issue here #20

## Purpose

Added all the ladder based on rating, with a total of 11 ladder (+-1100 Problems)

## Approach
- I used web scraping to get all the rating based ladder in the original static A20J site, and parsed it into the array format in main/ladder.py
- Added a new form in templates/index.html with a name "rating", then add the handler in main/views.py
- Adjust the form-box padding a little bit to compensate the added form

a2oj

### CODE REVIEW

**Comment by atpug22** [comment]
LGTM. Thanks!

**Comment by atpug22** [comment]
@subodhk01 PTAL.

**Review by subodhk01 — CHANGES_REQUESTED** [review]
Thanks for the contribution and the PR!

Everything looks perfect, just a small detail: Now that the user has 2 options to select from, "By Rating" or "By Division", it is a little unclear that the user only has to select any one of them, it would be really nice if we have some help text or simply an **OR** between the dropdowns which would indicate that only one of the two options have to be selected. I think the latter one seems better. 
Screenshot 2021-03-23 at 19 54 17

Can you implement it @abdulrcs ?

**Comment by abdulrcs** [comment]
Sure thing, I've added the or divider with pure bootstrap.
image

**Review by subodhk01 — APPROVED** [review]
LGTM, Thanks for your contribution @abdulrcs !

**Pull request merged**
