### PR TITLE
Moved to 2 version of Codeforces API PY

### PR DESCRIPTION
**Pull request by VadVergasov**
* Updated requirements.txt
* Updated .gitignore
* Updated to Codeforces API py

### CODE REVIEW

**Comment by subodhk01** [comment]
Hey @VadVergasov,
Thank you for the pull request but there seems to be some problem with changes. I've deployed the PR to https://pipeline1-master-hg4vpp48bup9n.herokuapp.com/. Please take a look

**Comment by VadVergasov** [comment]
Codeforces is down for now, it will be available tomorrow.

**Comment by subodhk01** [comment]
Ohh, cool

**Comment by VadVergasov** [comment]
https://test-app-for-github.herokuapp.com/ here you can test the latest master branch from my fork.

**Pull request closed without merging**
